org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.caching=true

# Mod metadata
mod_id=vectrum
mod_name=Vectrum
mod_version=0.1.0
mod_group=io.github.fishgames.vectrum
mod_authors=Fooshy
mod_description=Vectrum - a Minecraft mod for Fabric, Forge and NeoForge.
mod_license=All Rights Reserved

# Mekanism runtime jar in the Forge/NeoForge run configurations (remove the leading # to enable)
withMekanism=true
