org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.caching=true

# --- Mod-Metadaten (gelten fuer alle Loader und Versionen) ---
mod_id=vectrum
mod_name=Vectrum
mod_version=0.1.0
mod_group=io.github.fishgames.vectrum
mod_authors=Fooshy
mod_description=Vectrum - a Minecraft mod for Fabric, Forge and NeoForge.
mod_license=All Rights Reserved
