# NeoForge fuer 1.20.1 ist noch der "Legacy"-Fork von Forge (net.neoforged:forge) und wird
# von Architectury Loom deshalb als Forge-Plattform behandelt.
loom.platform=forge

java_version=17
pack_format=15

neoforge_version=47.1.106

# Optional: Parchment-Parameternamen (auskommentieren zum Deaktivieren)
parchment_version=2023.09.03
